# Generated by Django 3.0.5 on 2020-04-23 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgmessages', '0002_auto_20200423_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgmessage',
            old_name='username',
            new_name='author_id',
        ),
    ]
